project:
  type: website
  output-dir: docs

website:
  title: "Allen Bush-Beaupré"
  site-url: "https://www.allenbushbeaupre.com"
  description: "Personal website of Allen Bush-Beaupré, PhD student in ecological statistics and agricultural entomology at Université de Sherbrooke"
  navbar:
    background: dark
    foreground: light
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Consultations CREUS"
        file: consultation.qmd
      - posts.qmd
      - text: "Publications"
        file: publications.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:https://github.com/abushbeaupre/personal_website/tree/main:

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

